### ISSUE TITLE
didInsertElement and willDestroyElement should call super()

### ISSUE THREAD

**Issue by adambedford** [IliasDeros/ember-ds-inline-edit#2]
`didInsertElement` and `willDestroyElement` are overridden in the component  to register and unload event handlers, however core ember component behavior is never invoked because `this._super(...arguments)` isn't called.

I think this is the cause of some errors that I'm experiencing, particularly this one:
```
Cannot call writeWatching after the object is destroyed.
```

**Comment by IliasDeros** [comment]
Added `_super` calls in 12fa0f0ea60492ece5132e0b66395b9b6db388c7
